-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "inn" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "ogrn" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "kpp" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "companyType" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "legalAddress" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "directorName" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "verificationStatus" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "verificationDocs" TEXT[];
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "verificationData" JSONB;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "verifiedAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "rejectedReason" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Tenant_inn_key" ON "Tenant"("inn");
